<?php

namespace KovacsLaci\LaravelSkeletons\Services;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class RouteGenerator extends AbstractGenerator
{

    public function generate(): ?array
    {
        // Determine if auth middleware is available
        $hasAuthMiddleware = in_array('auth', array_keys(app('router')->getMiddleware()));

        $stubFileName = $hasAuthMiddleware ? self::stub_path('routes_auth.stub') : self::stub_path('routes.stub');
        try {
            $stubContent = self::getStubContent($stubFileName);
        }
        catch (\Exception $e) {
            $this->command->error($e->getMessage());
            return null;
        }
        $controller = "{$this->modelName}Controller";

        $placeholders = [
            '{{ controller }}' => $controller,
        ];
        $content = $this->replacePlaceholders($stubContent, $placeholders);
        $filePath = self::getPath(base_path("routes/{$this->tableName}.php"));
        $this->createBackup($filePath);
        File::put($filePath, $content);
        $this->generatedFiles[] = $filePath;
        $this->updateWebRoutes();

        $this->command->info("✅ Routes for {$this->modelName} created successfully in routes" . DIRECTORY_SEPARATOR . "{$this->tableName}.php");

        return [
            'generated_files' => $this->generatedFiles,
            'backup_files'    => $this->backupFiles,
        ];
    }

    public function updateWebRoutes()
    {
        $webRoutes = base_path("routes"  . DIRECTORY_SEPARATOR . "web.php");

        // Read the existing web.php content
        $webContent = File::exists($webRoutes) ? File::get($webRoutes) : "<?php\n\n";

        // Add require_once statements for only the files generated by this class
        foreach ($this->generatedFiles as $filePath) {
            $relativePath = Str::replace(base_path() . DIRECTORY_SEPARATOR, '', $filePath);
            $requireLine = "require_once base_path('{$relativePath}');";

            if (!Str::contains($webContent, $requireLine)) {
                $webContent .= $requireLine . "\n";
            }
        }

        // Write the updated content back to web.php
        File::put($webRoutes, $webContent);
        $this->command->info("web.php updated with route file imports.");
    }

    public function rollback(): void
    {
        foreach ($this->generatedFiles as $filePath) {
            if (File::exists($filePath)) {
                self::removeRequireFromWebRoutes($filePath);
            }
        }
        parent::rollback();
    }

    public static function removeRequireFromWebRoutes(string $filePath)
    {
        $webRoutes = self::getPath(base_path("routes/web.php"));

        // Check if web.php exists
        if (!File::exists($webRoutes)) {
            echo "\n❗web.php not found. Skipping removal of require instruction.";
            return;
        }

        // Read the content of web.php
        $webContent = File::get($webRoutes);

        // Generate the require_once line to remove
        $relativePath = Str::replace(base_path() . DIRECTORY_SEPARATOR, '', $filePath);
        $requireLine = "require_once base_path('$relativePath');";

        // Remove the line if it exists
        if (Str::contains($webContent, $requireLine)) {
            $webContent = Str::replace($requireLine . "\n", '', $webContent);
            File::put($webRoutes, $webContent);
            echo "Removed require instruction for $relativePath from web.php.\n";
        }
    }
}
